### ISSUE TITLE
error when lending btc, and depositing ETH

### ISSUE THREAD

**Issue by thanhnhi1** [script3/yieldblox-beta#44] opened 2021-10-06 23:28 UTC
when borrowing btc with a smaller amount sent, error message can't borrow
error when loading ETH, can't deposit when manually, instead of max

![ybx1](https://user-images.githubusercontent.com/39213949/136296957-dbf074ee-cfb2-4372-9515-628a5b8d5c76.png)
`AAAAAgAAAAA9XfhqUzsD+jNssNWX8uvtB5obQAniT3elAPLuHFhDZwAAF3AAA6f7AAAADAAAAAEAAAAAAAAAAAAAAABhXjBXAAAAAQAAAAd5YnhNaW50AAAAAAYAAAAAAAAAEAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAABAAAAAD1d+GpTOwP6M2yw1Zfy6+0HmhtACeJPd6UA8u4cWENnAAAAAUJUQwAAAAAANRJNNmxISmOJOzNbiJ4iTeYYNCXVqF7saTpMAgw2tXEAAAAAAJiWgAAAAAEAAAAAzHhMSdyMUNgnSasaFDFeTS7WXdHIM/DVffpsxTADrfwAAAAOAAAAAmwwMEJUQwAAAAAAAAAAAADMeExJ3IxQ2CdJqxoUMV5NLtZd0cgz8NV9+mzFMAOt/AAAAAAAmJaAAAAAAwAAAAAAAAAAPV34alM7A/ozbLDVl/Lr7QeaG0AJ4k93pQDy7hxYQ2cAAAADAAAAAQAAAAAAAAAAAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAAAAAAAAAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAAEAAAAAAAAAAAAAAABAAAAAMx4TEncjFDYJ0mrGhQxXk0u1l3RyDPw1X36bMUwA638AAAAEQAAAAEAAAAAGi10EZ2Rq5V5wVRUDZcWxFk0XlhmdZwwGxeRRAniJDEAAAABAAAAAIocaAtkXN0c7+djpQ/d6jqLeQW8zXFCDCK63mffpjieAAAAAnUwMEJUQwAAAAAAAAAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAAAAAOYJMAAAAAQAAAAAaLXQRnZGrlXnBVFQNlxbEWTReWGZ1nDAbF5FECeIkMQAAABMAAAACdTAwQlRDAAAAAAAAAAAAABotdBGdkauVecFUVA2XFsRZNF5YZnWcMBsXkUQJ4iQxAAAAAIocaAtkXN0c7+djpQ/d6jqLeQW8zXFCDCK63mffpjieAAAAAABF58gAAAAAAAAAAhyXJzMAAABAEoYXnDNy2UycBZF8+qgEUHpMNbJ5KujFA1whMI8iZsSUFdWBwl8wRJOsqJa5r5GiZ2VD1PVK+iHrR8ZSTd1vC6ICYd8AAABA4UesIxXYbu+AN62J+LdYn43MxLf45i09USzxpsXyhTC3hoQ0qxAfXfW3GIUmBuqGJHk6MmxohGBn8E8abkN9DQ==`

**Comment by mootz12** [comment] 2021-10-06 23:31
Duplicate of issue 6

**Closed by mootz12** 2021-10-06 23:31 UTC
