### ISSUE TITLE
"Manage Collateral" Mixed values when clicking on edit icon in Market. (Video attached)

### ISSUE THREAD

**Issue by StellarStoic** [script3/yieldblox-beta#304] opened 2021-10-13 19:47 UTC
Values on the first click are shown the values of a previously clicked asset in Manage Collateral on the Market screen. The bug is only on the first click on asset. Clicks after that are showing the correct values.

https://user-images.githubusercontent.com/34000272/137202208-7a6a9dd9-526c-4063-9cd3-b3ec40ab7bd3.mp4

**Comment by mootz12** [comment] 2021-10-14 02:48
Appears to be a duplicate of https://github.com/script3/yieldblox-beta/issues/269

**Closed as completed by mootz12** 2021-10-14 02:48 UTC
Labels: duplicate
