### ISSUE TITLE
Unable To Claim YBX brave & google chrome Same story

### ISSUE THREAD

**Issue by ocydlevie** [script3/yieldblox-beta#327] opened 2021-10-15 03:18 UTC
![1](https://user-images.githubusercontent.com/92197146/137426717-aa83562d-e9ae-4dea-ba0d-a82367dc1816.jpg)
![2](https://user-images.githubusercontent.com/92197146/137426720-ecefd0ee-7161-45e6-98f0-b8d334554a53.jpg)
![3](https://user-images.githubusercontent.com/92197146/137426723-a8ba6b72-51bb-43ed-ad1d-ae02f170449b.jpg)
![4](https://user-images.githubusercontent.com/92197146/137426724-7b5c7b83-d7c2-49b8-a72c-fe198a24c91a.jpg)
Pict 1-4 i try to claim YBX and borrow in the brave browser. show the error result

![5](https://user-images.githubusercontent.com/92197146/137426766-40c5dfc6-ed90-4f11-abd2-74e1e5f2fc0b.jpg)
![6](https://user-images.githubusercontent.com/92197146/137426768-43ef0bb0-6c85-4c62-b08b-760c706d519f.jpg)
Pict 5-6 itry to claim ybx and borrow in the chrome browser show same error result

My PK : GCBSRDTSGTEC23MA3BWE5X422CA2GHIFSFACCB426G3M7Y6NTFPCDEGI
My Keybase username : adamdeviyanto

**Comment by mootz12** [comment] 2021-11-08 13:47
Marked as duplicate of https://github.com/script3/yieldblox-beta/issues/327

**Closed as completed by mootz12** 2021-11-08 13:47 UTC
Labels: duplicate
