### ISSUE TITLE
Token yield % for lending jumped significantly after daily claim

### ISSUE THREAD

**Issue by defj** [script3/yieldblox-beta#160] opened 2021-10-08 00:42 UTC
Token yield % for lending appears to be either incorrect or significantly increased after the daily claim. Previously ETH lending was around 150% now nearly 3000%

![image](https://user-images.githubusercontent.com/11483548/136480721-2340609e-9f24-429a-aa7a-fb344929c873.png)

**Comment by coolrobiul** [comment] 2021-10-08 01:49
Same for me
But after some time it was fixed for me

**Comment by mootz12** [comment] 2021-10-12 00:50
Duplicate of https://github.com/script3/yieldblox-beta/issues/119

**Closed as completed by mootz12** 2021-10-12 00:50 UTC
Labels: duplicate, frontend
