### ISSUE TITLE
Asset repayment health factor and collateral issue

### ISSUE THREAD

**Issue by theboycoder** [script3/yieldblox-beta#283] opened 2021-10-12 23:44 UTC
Before the repayWithCollateral update my account was bugged with not being able to repay the loan, but during the repayment the health factor showed it would go up to the safe point around 1.00 all of the loans and even more for the larger ones, but it only went up by 0.1 with small loans being blocked due the low health. Today after the patch my health factor on the repayment screen doesn't go up to the safe spot despite trying to pay large sums, I tried this with small and large balance payments. I didn't go through with the payment because I would repay(lose) the assets without my health factor moving beyond the safe point. I would almost have to liquidate the whole account and it would barley go into the safe spot.

Edit 1: I this tried again after the script, the small balance loans don't move at all, the large ones for ETH and USDC both go to the same safe health factor despite(1.03) the varying difference in both of the large loans which is pretty much the whole account if repaid. But when I try to pay back from the balance in the wallet which is less than 30k for USDC or ETH the health factor moves up more from a under 30k deposit repayment than from the large repayment from all the loans collateral, considering the margin difference between the loans collateral and the small balance repayment from the deposit repayment.  

Edit 2: I still have failure to repay back the EURT loan with the same error as failure to repay due to low health, while using the max pay for the loan after the repaymentWithCollateral  

**Edit 2 for EURT payment failure**
![edit 2](https://user-images.githubusercontent.com/45983304/137047605-dea912cc-d60a-4bcd-9d8e-11ecd00120e6.png)

**Edit 1**
![714c557d9c486832f3072d3d25204d27](https://user-images.githubusercontent.com/45983304/137045988-1dbe93c2-6ebf-43cd-8072-36e728922f3f.png)

**Edit 1**
![a6564a8860590e3456b1adb31fc9b4ed](https://user-images.githubusercontent.com/45983304/137045992-2c4cbe95-8abb-42dc-9fc7-15a4b9c64dab.png)

**Before Patch**
![before patch](https://user-images.githubusercontent.com/45983304/137042870-583f2010-b76b-426c-acdc-c81d49b166c0.png)

**After Patch**
![after patch](https://user-images.githubusercontent.com/45983304/137042896-26de9a67-ce79-4083-98f7-250cdd19e40f.png)

**Confirms the repayment with health factor barley going up**
![after patch 2](https://user-images.githubusercontent.com/45983304/137042996-eed4d34c-440a-419f-b9a4-a369dcec0b6f.png)

**Comment by markuspluna** [comment] 2021-10-25 15:46
This was a bug with repayment. It was fixed in the most recent update

**Closed as completed by markuspluna** 2021-10-25 15:46 UTC
Labels: duplicate

**Comment by markuspluna** [comment] 2021-11-08 20:29
Duplicate of #240
