### ISSUE TITLE
stake a little ybx make healt factor to sky

### ISSUE THREAD

**Issue by LorDDark6660** [script3/yieldblox-beta#316] opened 2021-10-14 12:46 UTC
Stake small amount of ybx make HF big

![3](https://user-images.githubusercontent.com/92062140/137319914-00c1dfd8-f346-4afd-9515-7fdb76bcdd29.png)

tx hash: 55a8a5d835de5879ca515f18e5a07daac5d33e69b8459d6085ddf8ea6e78a54f

![4](https://user-images.githubusercontent.com/92062140/137320220-01a4e8f2-5775-4db4-a58e-fb8323bd5d5b.png)

**Comment by arnob016** [comment] 2021-10-14 13:19
What it is supposed to be : 

![image](https://user-images.githubusercontent.com/74468064/137325299-dec00ef6-2084-4f37-8c45-0cfdac279ee0.png)

What it becomes : 

![image](https://user-images.githubusercontent.com/74468064/137325374-ecd43d89-5b0c-45a7-9395-e2225664a1d0.png)

**Comment by markuspluna** [comment] 2021-11-08 20:35
This was a duplicate of the price bot bug

**Closed as completed by markuspluna** 2021-11-08 20:35 UTC
Labels: duplicate
