### ISSUE TITLE
1 stroop stays back no matter how much I repay.

### ISSUE THREAD

**Issue by arnob016** [script3/yieldblox-beta#179] opened 2021-10-08 09:03 UTC
I tried repaying a single stroop that stays back for 14-15 times, but it doesnt work.

Github doesn't support .webm so please watch it from drive 
Link : https://drive.google.com/file/d/10SiiBTt7adfyq0Je1K4C1XSU8jcYDQWG/view?usp=sharing

Additional Screenshots:

![image](https://user-images.githubusercontent.com/74468064/136528945-ca875c99-15e3-41f1-a5f4-c4bcfee230e2.png)
![image](https://user-images.githubusercontent.com/74468064/136528970-89bcd594-555f-473b-9ffe-f99ff74b06ea.png)
![image](https://user-images.githubusercontent.com/74468064/136528981-a83b8967-7d5d-487d-bde2-b3893a13fd67.png)
![image](https://user-images.githubusercontent.com/74468064/136529073-0872b29a-467e-4695-939b-b1d21f09ef07.png)
![image](https://user-images.githubusercontent.com/74468064/136529119-d9c36300-60a1-4dee-9141-e503b4ca23df.png)
![image](https://user-images.githubusercontent.com/74468064/136529178-7a49f43a-83c6-4f16-83d5-2f889a362883.png)

**Comment by arnob016** [comment] 2021-10-08 09:06
Update 1: 
I changed my interest type into a fixed rate. Yet 1 stroop stays back.

![image](https://user-images.githubusercontent.com/74468064/136529338-7bf97d84-1bf1-4a04-9dde-60cd2bf0f964.png)
![image](https://user-images.githubusercontent.com/74468064/136529487-550e7f9b-ac2b-46de-98b5-2fec15209e8c.png)
![image](https://user-images.githubusercontent.com/74468064/136529555-e2f0f0be-c7fa-43c2-b45a-fcecb6c42c6b.png)
![image](https://user-images.githubusercontent.com/74468064/136529655-7560fd87-4baf-41c1-9e0d-3e1e9eec6a57.png)
![image](https://user-images.githubusercontent.com/74468064/136529703-b5133b66-814f-4643-b0ae-ee1c0532af33.png)

**Comment by mootz12** [comment] 2021-10-13 20:35
This is a duplicate of https://github.com/script3/yieldblox-beta/issues/32

**Closed as completed by mootz12** 2021-10-13 20:35 UTC
Labels: duplicate, protocol
