### ISSUE TITLE
Stake and Unstake Report

### ISSUE THREAD

**Issue by ygusmada** [script3/yieldblox-beta#183] opened 2021-10-08 10:36 UTC
I have did some stuff with stake and unstake on Yieldblox! I try to input zero, minus and over balance and get the report. I got two that i think need some improvement, here are documentation about that.

_Note
✅ : No problem
⚠️: I think need some improvement_

### STAKE
**Staking zero balance** ⚠️
We can do but it just like submitted transaction to the network. Nothing happened!
![image](https://user-images.githubusercontent.com/28614308/136541349-6444d19c-3c1a-4b47-af12-b43305d222aa.png)
![image](https://user-images.githubusercontent.com/28614308/136541366-36f80483-83ef-4f54-b80d-11dd9919e615.png)

**Staking minus balance** ✅
No no no… We can’t do this!
![image](https://user-images.githubusercontent.com/28614308/136541400-f64deb6b-8b04-40d3-9db4-b9306f4c5308.png)
![image](https://user-images.githubusercontent.com/28614308/136541413-19e22024-a2dd-4617-8965-8425be01b13c.png)

**Staking more than available balance** ✅
We can't do this!
![image](https://user-images.githubusercontent.com/28614308/136541531-c7f872d6-6e05-4186-921f-693f20e17c53.png)
![image](https://user-images.githubusercontent.com/28614308/136541561-9cb7d156-f856-4471-8d8b-356e98b84ee6.png)

### UNSTAKE
**Unstaking minus balance** ✅
We can't do this!
![image](https://user-images.githubusercontent.com/28614308/136541716-7d166e7b-72c3-4742-bec8-1eb7d46c6c40.png)
![image](https://user-images.githubusercontent.com/28614308/136541724-cdc3cba0-fda2-42f9-bc44-f85adbfebab8.png)

**Unstaking zero balance** ✅
We can't do this!
![image](https://user-images.githubusercontent.com/28614308/136541745-9f4cb04b-6fe2-4e1f-8009-e89bd5179ed5.png)
![image](https://user-images.githubusercontent.com/28614308/136541772-006beea9-42b0-4845-a246-1af2bbd02cdd.png)

**Unstaking more than available balance** ⚠️
We can do this, but we still got balance that we have. Example: we had stake 10 YBX and got 2 sYBX if we input 10000 to unstake it, it can be happen but we still got balance that we have (10 YBX). 
![image](https://user-images.githubusercontent.com/28614308/136541673-ada8ebee-da6d-4b54-8883-d660774498cb.png)
![image](https://user-images.githubusercontent.com/28614308/136541689-257323ca-f5b0-43dc-8d23-555101200feb.png)

**Comment by ygusmada** [comment] 2021-10-08 13:10
Staking with zero balance will be good if the function same as unstake that will pop-up error notification when we try to submit transaction

**Comment by mootz12** [comment] 2021-10-13 20:39
duplicate of https://github.com/script3/yieldblox-beta/issues/26

**Closed as completed by mootz12** 2021-10-13 20:39 UTC
Labels: frontend, suggestion

**Comment by ygusmada** [comment] 2021-11-11 01:11
Discord = ygusmada#1930
email = yugusmada@gmail.com
yieldbox testnet address = GAFS7FTPOBE477IL2CG2UCWB6VQTBHVJEC2KEKJSJW2BHIR5XHLBFJ7T
Stellar public address = GCZGERVJLJOEJG3RK3ND6LXUGMFLYUEU6XWXD7LXVSUPP7EQTCBGR2K5
