### ISSUE TITLE
Repaying USDC leaves 0.001918 USDC behind.

### ISSUE THREAD

**Issue by arnob016** [script3/yieldblox-beta#150] opened 2021-10-07 22:10 UTC
![image](https://user-images.githubusercontent.com/74468064/136468854-9aac9f53-f010-4844-ab5b-10dcc46388ff.png)

This also happened when I was repaying my borrowed ETH. It's kind of annoying.

**Comment by mootz12** [comment] 2021-10-12 13:34
Duplicate of https://github.com/script3/yieldblox-beta/issues/32

**Closed as completed by mootz12** 2021-10-12 13:34 UTC
Labels: duplicate, frontend
