### ISSUE TITLE
Repayed all USDC, But still displays as borrowed $0.00 

### ISSUE THREAD

**Issue by tourBermuda** [script3/yieldblox-beta#127] opened 2021-10-07 16:06 UTC
Repayed all USDC, But still displays as borrowed $0.00. When I open the window to replay, and I click max it populates with a 1USDC.
![Screen Shot 2021-10-07 at 12 55 44 PM](https://user-images.githubusercontent.com/10064984/136422156-015c388c-6095-4796-a04c-6ec239e41518.png)
![Screen Shot 2021-10-07 at 12 56 07 PM](https://user-images.githubusercontent.com/10064984/136422204-12a82d2c-006d-4e78-a90c-d6503562ae81.png)

**Comment by mootz12** [comment] 2021-10-12 13:32
Duplicate of https://github.com/script3/yieldblox-beta/issues/32

**Closed as completed by mootz12** 2021-10-12 13:32 UTC
Labels: duplicate
