### ISSUE TITLE
Health factor and APY tab goes spike

### ISSUE THREAD

**Issue by f0xie7** [script3/yieldblox-beta#233] opened 2021-10-10 01:22 UTC
After claimin YBX and stake them, the Health Factor goes from 1.15 to 2.25, and APY from 3% to 1.12k%
I dont know is it enable me to borrow more amount or not, imafraid i got liquidated after do it.
I expected because not many people staking earned YBX at that day to the YBX pools (?), it probably affect YBX weight at the moment.

![image](https://user-images.githubusercontent.com/91896561/136677892-02a1f9c6-d810-4366-8a3e-a7e01de6b897.png)
![image](https://user-images.githubusercontent.com/91896561/136677926-88e94b72-d773-473c-8fb2-3a07f33103fe.png)

**Comment by f0xie7** [comment] 2021-10-10 01:34
It goes normal now
![image](https://user-images.githubusercontent.com/91896561/136678180-6f12486c-cbeb-432c-ae2a-09f80a966236.png)

**Comment by defj** [comment] 2021-10-10 01:46
It allows you to borrow more, my health factor went from 1.15 -> 1.47 letting borrow another 600k USDC
health factor then dropped to 0.74

**Comment by mootz12** [comment] 2021-10-13 21:24
This is a duplicate of https://github.com/script3/yieldblox-beta/issues/119

**Closed as completed by mootz12** 2021-10-13 21:24 UTC
Labels: duplicate
