### ISSUE TITLE
Repay problem

### ISSUE THREAD

**Issue by Julitasa** [script3/yieldblox-beta#93] opened 2021-10-07 03:51 UTC
![image](https://user-images.githubusercontent.com/92071810/136317363-f1c04f42-98bb-46e7-be27-5757b9d92da3.png)

Trying to repay after borrow for 10 ETH, but not gonna fully paid off and still showing borrow almost zero balance, the minimum value isn't fully payable even after click on max repay amount.
recent transaction :
https://stellar.expert/explorer/testnet/tx/eff77b4edf6a2760b1644a6a30eb5284b8cdad7e86a1d62358db0eeb71eb7fa5
https://stellar.expert/explorer/testnet/tx/a2650c0e4636bb64557eabfdeb7c6682d7f8e40c15a098e3e5d0050097f40bd9
https://stellar.expert/explorer/testnet/tx/f146c1cc81378881565f82f3d48d4dd128121443a113e97e3d48ab17231775ac

**Comment by mootz12** [comment] 2021-10-12 13:29
Duplicate of https://github.com/script3/yieldblox-beta/issues/32

**Closed by mootz12** 2021-10-12 13:29 UTC
Labels: duplicate
