### ISSUE TITLE
Freighter & Rabet problem with Deposit

### ISSUE THREAD

**Issue by hasToDev** [script3/yieldblox-beta#21] opened 2021-10-06 22:39 UTC
**Issue :**
Try to Deposit ETH with both Freighter & Rabet, both fail.

**Tools :**
1. Freighter wallet
2. Rabet wallet
3. Firefox browser

**Step to reproduce :**
1. on Market page, click ETH
2. click MAX on Deposit Amount
3. click Deposit & then Confirm

**Screenshot :**
This happened with Rabet 
![Rabet-Failed-Invalid-XDR](https://user-images.githubusercontent.com/44645201/136293206-10ccde37-3561-4a26-91aa-8c23c5c09951.jpg)

and this with Freighter :
![Freighter-Went-Wrong](https://user-images.githubusercontent.com/44645201/136293246-0603be2d-b027-4819-91a5-50114cae19ab.jpg)

**Comment by mootz12** [comment] 2021-10-08 17:14
marked as duplicate of https://github.com/script3/yieldblox-beta/issues/6

**Closed as completed by mootz12** 2021-10-08 17:14 UTC
Labels: duplicate, misc
