### ISSUE TITLE
APY percentage?

### ISSUE THREAD

**Issue by cryptodmc771** [script3/yieldblox-beta#311] opened 2021-10-14 12:18 UTC
<img width="1440" alt="Screen Shot 2021-10-14 at 8 17 02 AM" src="https://user-images.githubusercontent.com/92388247/137315710-3a4abb74-eaae-4220-b107-ef4fcc0ee063.png">

**Comment by arnob016** [comment] 2021-10-14 12:22
duplicate of #233 and #119

**Closed as completed** 2021-10-27 17:34 UTC
Labels: duplicate
